name: Create Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: membrane-io/mnode
          token: ${{ secrets.GITHUB }}

      - name: Determine version
        id: version
        run: |
          cd mctl
          echo "VERSION=$(cat Cargo.toml | grep -E '^version *= *".*' | awk '{print $3}' | tr -d '"')" >> "$GITHUB_OUTPUT"

      - name: Download Linux x86 artifact
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: membrane-io/mnode
          token: ${{ secrets.GITHUB }}
          artifact_name: mctl-${{steps.version.outputs.VERSION}}-linux-x86.zip
          wait_seconds: 60

      - name: Download MacOS x86 artifact
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: membrane-io/mnode
          token: ${{ secrets.GITHUB }}
          artifact_name: mctl-${{steps.version.outputs.VERSION}}-macos-x86.zip
          wait_seconds: 60

      - name: Download MacOS Arm artifact
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: membrane-io/mnode
          token: ${{ secrets.GITHUB }}
          artifact_name: mctl-${{steps.version.outputs.VERSION}}-macos-arm.zip
          wait_seconds: 60

      - name: Compute SHA256
        run: sha256sum mctl-*.zip > sha256.txt

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          name: "Membrane mctl"
          tag_name: ${{steps.version.outputs.VERSION}}
          fail_on_unmatched_files: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            mctl-${{steps.version.outputs.VERSION}}-*.zip
            sha256.txt
