name: Create Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: membrane-io/mnode
          token: ${{ secrets.GITHUB }}

      - name: Determine version
        id: version
        run: |
          cd mctl
          echo "VERSION=$(cat Cargo.toml | grep -E '^version *= *".*' | awk '{print $3}' | tr -d '"')" >> "$GITHUB_OUTPUT"

      - name: Verify Cargo Version
        run: |
          tag_version="${{ steps.version.outputs.VERSION }}"
          cargo_version=$(cat mctl/Cargo.toml | grep -E '^version *= *".*' | awk '{print $3}' | tr -d '"')

          if [ "$tag_version" != "$cargo_version" ]; then
            echo "Tag version ($tag_version) and Cargo.toml version ($cargo_version) do not match. Aborting the workflow."
            exit 1
          fi
      
      - name: Verify if release exists
        id: release_exists
        run: |
          existing_tags=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/membrane-io/mnode/tags")
          tag_version="${{ steps.version.outputs.VERSION }}"
          tag_exists=false
          for tag in $(echo "$existing_tags" | jq -r '.[].name'); do
            if [ "$tag" = "$tag_version" ]; then
              tag_exists=true
              break
            fi
          done
          if [ "$tag_exists" = true ]; then
            echo "Release $tag_version already exists. Aborting the workflow."
            exit 1
          fi


      - name: Download Linux x86 artifact
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: membrane-io/mnode
          token: ${{ secrets.GITHUB }}
          artifact_name: mctl-${{steps.version.outputs.VERSION}}-linux-x86.zip

      - name: Download MacOS x86 artifact
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: membrane-io/mnode
          token: ${{ secrets.GITHUB }}
          artifact_name: mctl-${{steps.version.outputs.VERSION}}-macos-x86.zip

      - name: Download MacOS Arm artifact
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: membrane-io/mnode
          token: ${{ secrets.GITHUB }}
          artifact_name: mctl-${{steps.version.outputs.VERSION}}-macos-arm.zip

      - name: Download MacOS Arm artifact
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: membrane-io/mnode
          token: ${{ secrets.GITHUB }}
          artifact_name: mctl-${{steps.version.outputs.VERSION}}-windows.zip

      - name: Unzip zips
        run: |
          mkdir out
          unzip mctl-${{steps.version.outputs.VERSION}}-linux-x86.zip -d out/
          unzip mctl-${{steps.version.outputs.VERSION}}-macos-x86.zip -d out/
          unzip mctl-${{steps.version.outputs.VERSION}}-macos-arm.zip -d out/
          unzip mctl-${{steps.version.outputs.VERSION}}-windows.zip -d out/
          ls out

      - name: Compute SHA256
        run: sha256sum out/mctl-*.zip > sha256.txt

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          name: "Membrane mctl"
          tag_name: ${{steps.version.outputs.VERSION}}
          fail_on_unmatched_files: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            out/mctl-${{steps.version.outputs.VERSION}}-*.zip
            sha256.txt
